export { default as Nivedika } from './nivedika_gupta.jpg'
export { default as Nivedika_square } from './Nivedika Gupta-square.png'
export { default as Pankaj } from './Pankaj Dhingra.png'
export { default as Candy } from './Candy.png'
export { default as Kriti } from './Kriti Aggarwal.png'
export { default as Preshita } from './Preshita Pusalkar.png'
export { default as Meet } from './Meet rasaniya.png'
export { default as Aritri } from './Aritri Mandal.png'
export { default as Aditya } from './Aditya.png'
export { default as Naman } from './Naman Aggarwal.png'
export { default as Ritheesh } from './Ritheesh kumar.png'
export { default as Vishakha } from './Vishakha Ahuja.png'
export { default as AboutBanner } from './AboutBanner.jpg'
export { default as AboutBannerPhone } from './AboutBannerPhone.jpg'
export { default as AboutVer } from './AboutVer.jpg'
export { default as AboutHori } from './AboutHori.jpg'
export { default as Self } from './Selfless Purpose.jpg'
export { default as Dedication } from './Dedication.jpg'
export { default as Focused } from './Focused Areas.jpg'
export { default as Prachi } from './Prachi.png'
export { default as Vishal } from './Vishal.png'
export { default as Yesu } from './Yesu.png'
export { default as Manasree } from './Manasree.png'
export { default as Kalpesh } from './Kalpesh.png'
export { default as Tanisha } from './Tanisha.png'
export { default as Priyanka } from './Priyanka.png'
export { default as Sanyukta } from './Sanyukta.png'
export { default as Goouri } from './Goourie.jpg'
export { default as Sunita } from './Sunita.jpg'
export { default as Manish } from './Manish.jpg'
