export { default as Trustworthy1 } from './Icon-1000-percent-Trustworthy1.webp';
export { default as Support1 } from './Icon-24x71.png';
export { default as NGOs1 } from './Icon-1000+NGOs.1.png';
export { default as Payments1 } from './Icon-All Payments 1.png';
export { default as Extend_reach } from './Icon-Extend your Reach.webp';
export { default as Coach1 } from './Icon-Fundraising Coach1.png';
export { default as Processing } from './Icon-No Processing.webp';
export { default as Campaign_setup } from './Icon-Simple campaign setup.webp';
export { default as Tax1 } from './Icon-Tax Benefits1.png';
export { default as Dashboard1 } from './Icon-User-Friendly Dashboard1.png';
export { default as Medical } from './1.png';
export { default as Others } from './others.png';
export { default as Happy_Children } from './Happy-children-Impaac.webp';
export { default as Happy_girl } from './Happy-girl-Impaac.webp';
export { default as Happy_Women } from './Happy-women-Impaac.webp';
export { default as Patient } from './Patient-Impaac.webp';
export { default as Raise_Funds1 } from './Raise-Funds.webp';
export { default as Donate_Funds } from './Donate-Funds.webp';
export { default as Callback } from './Callback-Impaac.webp';
export { default as JoinHands } from './join-hands.webp';
export { default as NoPlastic } from './no-plastic.webp';
export { default as Poverty_india } from './Poverty-India.webp';
export { default as Reliable_Platform } from './Reliable-Platform.webp';
export { default as Kid_Impaac } from './kid-impaac.webp';
export { default as Lady_Success } from './lady-success.png';
export { default as Old_Lady } from './oldlady-success.webp';
export { default as Artist_Success } from './artist-success.webp';
export { default as Ultimate_Charity } from './Ultimate-Charity.webp';
export { default as dog_success } from './dog_success.webp';
export { default as Donate_Picture } from './Donate-Picture.webp';