export const ngoDefaultValue = (ngo) => ({
    name: ngo?.name || '',
    registered_name: ngo?.registered_name || '',
    bio: ngo?.bio || '',
    email: ngo?.email || '',
    phone_number: ngo?.phone_number || '',
    street: ngo?.address?.street || '',
    area_code: ngo?.address?.area_code || '',
    city: ngo?.address?.city || '',
    state: ngo?.address?.state || '',
    country: ngo?.address?.country || '',
    have_reg: false,
    reg_number: ngo?.pan_card?.number || '',
    reg_doc: ngo?.pan_card?.document || '',
    have_pan: false,
    pan: ngo?.pan_card?.number || '',
    pan_card_doc: ngo?.pan_card?.document || '',
    have_twelve_a: false,
    twelve_a: ngo?.twelve_a?.number || '',
    twelve_a_doc: ngo?.twelve_a?.document || '',
    twelve_a_expiry: ngo?.twelve_a?.expiry_date || '',
    have_eighty_g: false,
    eighty_g: ngo?.eighty_g?.number || '',
    eighty_g_doc: ngo?.eighty_g?.document || '',
    eighty_g_expiry: ngo?.eighty_g?.expiry_date || '',
    ben_name: ngo?.account_details?.beneficiary_name || '',
    acc_no: ngo?.account_details?.account_no || '',
    acc_type: ngo?.account_details?.account_type || '',
    ifsc_code: ngo?.account_details?.ifsc_code || '',
    bank_doc: ngo?.account_details?.document || '',

    have_fcra: false,
    fcra_no: ngo?.fcra?.number || '',
    fcra_doc: ngo?.fcra?.document || '',
    fcra_expiry: ngo?.fcra?.expiry_date || '',
    f_ben_name: ngo?.fcra_account_details?.beneficiary_name || '',
    f_acc_type: ngo?.fcra_account_details?.account_type || '',
    f_acc_no: ngo?.fcra_account_details?.account_no || '',
    f_ifsc_code: ngo?.fcra_account_details?.ifsc_code || '',
    f_swift_code: ngo?.fcra_account_details?.swift_code || '',
    f_bank_doc: ngo?.fcra_account_details?.document || '',

    user_first_name: ngo?.users[0]?.first_name || '',
    user_last_name: ngo?.users[0]?.last_name || '',
    user_document_name: ngo?.users[0]?.doc_name || '',
    user_document_front: ngo?.users[0]?.doc_front_side || '',
    user_document_back: ngo?.users[0]?.doc_back_side || '',
    user_document_number: ngo?.users[0]?.doc_number || '',
    user_relation: ngo?.users[0]?.designation,

    website: ngo?.social_media?.website || '',
    instagram: ngo?.social_media?.instagram || '',
    facebook: ngo?.social_media?.facebook || '',
    youtube: ngo?.social_media?.youtube || '',
    linkedin: ngo?.social_media?.linkedin || '',
    twitter: ngo?.social_media?.twitter || '',
  });
